### ISSUE TITLE
Firefox wal theme doesn't change background on a lot of websites

### ISSUE THREAD

**Issue by millionsofplayers** [alexhulbert/nix#2]
![image](https://github.com/alexhulbert/SeaGlass/assets/15851867/71b37c59-721d-4602-9263-6905e8cd31c0)

on github it seems to just use the default darkreader colors

edit: nevermind, it uses the same colors. background is the same though
![image](https://github.com/alexhulbert/SeaGlass/assets/15851867/0ef8d27f-4a69-4b09-89b1-de92151b8aa1)

**Comment by alexhulbert** [comment]
In order to fix this, you have to turn off dark mode on the site level. Darkreader will only make a website dark mode if it's not already dark, unfortunately.

**Comment by millionsofplayers** [comment]
i still don't have a colored background (or at least as colored as it is in the terminal) but this looks better than it did before

**Comment by alexhulbert** [comment]
try using a color picker tool to check the background color and check it against your terminal background and the background color in ~/.cache/wal/colors. Lmk which ones match up.

Also if you're using pywal16, someone mentioned there's a bug in it that that makes the color too dark
