### ISSUE TITLE
Hyprchroma support for Hyprland 0.40.0?

### ISSUE THREAD

**Issue by overtoneblue** [alexhulbert/nix#3]
As the title suggests, im getting this build error when trying to add hyprchroma on NixOS, pinned to the hyprland 0.40.0 release in my flake:

 hyprland.url = "github:hyprwm/hyprland?ref=v0.40.0&submodules=1";
    # Hyprland workspace overview plugin
    hyprland-hyprspace = {
      url = "github:KZDKM/Hyprspace";
      inputs.hyprland.follows = "hyprland";
    };
    # Hyprland transparency magic
    hyprland-hyprchroma = {
      url = "github:alexhulbert/HyprChroma";
      inputs.hyprland.follows = "hyprland";
    };

error: builder for '/nix/store/y1n3iq5nnmmvk86xz71zhppvqvajac62-Hypr-DarkWindow-0.1.drv' failed with exit code…
┃        last 10 log lines:
┃        > src/main.cpp: In lambda function:
┃        > src/main.cpp:123:54: error: cannot convert 'PHLWINDOWREF' {aka 'std::weak_ptr<CWindow>'} to 'CWindow*'
┃        >   123 |         g_WindowInverter.ToggleInvert(g_pCompositor->m_pLastWindow);
┃        >       |                                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
┃        >       |                                                      |
┃        >       |                                                      PHLWINDOWREF {aka std::weak_ptr<CWindow>}
┃        > src/WindowInverter.h:18:32: note:   initializing argument 1 of 'void WindowInverter::ToggleInvert(CWindow*)'
┃        >    18 |     void ToggleInvert(CWindow* window);
┃        >       |                       ~~~~~~~~~^~~~~~
┃        > make: *** [Makefile:7: all] Error 1

**Comment by alexhulbert** [comment]
Updated the HyprChroma repo, try now. Works for me on the latest version of hyprland :+1:
