### ISSUE TITLE
Firefox pywal theme doesn't change background on any of sites.

### ISSUE THREAD

**Issue by reklatekoy** [alexhulbert/nix#4]
Firefox pywal theme doesn't change background on any of sites.
The dark theme of the site itself is disabled.
Only the text color changes.

![2024-06-04_01-12](https://github.com/alexhulbert/SeaGlass/assets/135157820/80017046-3d6f-41c4-ba4a-18cedc411f6f)

**Comment by alexhulbert** [comment]
Try disabling the built-in github/google dark modes. Darkreader doesn't work if the site is already dark

**Comment by reklatekoy** [comment]
Built-in dark mode disabled.
The background  doesn't change on any of the sites. Only the text color changes
For example wiki with and without darkreader enabled.
When darkreader is on background color is standard for darkreader #181a1b
![1](https://github.com/alexhulbert/SeaGlass/assets/135157820/56cc07a8-f4b5-4812-816d-5f285153fd9c)
![2](https://github.com/alexhulbert/SeaGlass/assets/135157820/8b1b5310-7902-4b66-98c1-96853f7b113b)

**Comment by alexhulbert** [comment]
Oh I forgot to add to the readme that you have to `chmod +x /opt/darkreader-pywal/index.js`

**Comment by alexhulbert** [comment]
@reklatekoy I know this is 5 months old but the issue was a typo in the readme. It said "studio" instead of "stdio". If you try again with a correct darkreader.json it'll work.
