### ISSUE TITLE
 HyprChroma plugin outdated.

### ISSUE THREAD

**Issue by hexavolta** [alexhulbert/nix#7]
can  you please update the HyprChroma plugin, i  updated my Arch setup for the first time in two months,luckily everything works fine after the update,except  the hyprchroma plugin failed to build since hyprland's version in Arch's repositories are updated to version 0.42,it's was an interesting major update for hyprland,so i couldnt resist to try it...
thank you in advance .

**Comment by alexhulbert** [comment]
Yeah totally, I'll have some free time on Monday to update it. If you're impatient, you can pull in the changes from the repo i forked and build manually. the merge conflicts usually aren't too bad.

**Comment by alexhulbert** [comment]
Updated to 0.43.0! Sorry it took so long. I've been abroad for the last month, so I've barely had time to sit down at my laptop.
