### ISSUE TITLE
Firefox wal theme doesn't change background on any websites

### ISSUE THREAD

**Issue by Rajala1404** [alexhulbert/nix#9]
I have the exact same issue as in #4 
It changes the color of the text but not the background the background is i think the default dark reader one regardless of if the site is in light or dark mode
![image](https://github.com/user-attachments/assets/68099836-c1d8-4142-8749-b27c8168f9c3)

This is the output of `node /opt/darkreader-pywal/index.js` if that helps

```
v{"type":"setTheme","data":{"darkSchemeBackgroundColor":"#00000014","darkSchemeTextColor":"#e5ccf614"},"isNative":true}
```

**Comment by alexhulbert** [comment]
Hi @Rajala1404, can you verify if only the color of links is changing? Or is the color of the text definitely matching your pywal configuration? Try changing the pywal theme on the fly and see if the text color obviously changes.

**Comment by Rajala1404** [comment]
I tried what you suggested @alexhulbert and the color of the links are changing but it looks like there changing because of userContent.css (that defines dark-darkreader-mode) and not actually the link to the index.js file. And I may add that I use librewolf but I tried the same exact setup in Firefox and there it also wouldn't work.

**Comment by alexhulbert** [comment]
@Rajala1404 Ah okay, I don't think librewolf uses the ".mozilla" directory since they're trying to not associate with Mozilla. The official librewolf FAQ suggests running the following commands:
```bash
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts

sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
```

If that doesn't fix your issue, close all browser windows and then open up a new browser window. Then, press Control+Alt+Shift+I and click "allow" to open a browser console. This will give you browser-wide error messages which should include some clues about the browser extension. Take a screenshot of the browser console (take more if you have to scroll up) and post that here. Then, run the following commands and post their output:

```bash
ls -hal ~/.librewolf/native-messaging-hosts
```

```bash
ls -hal /opt/darkreader-pywal
```

**Comment by Rajala1404** [comment]
@alexhulbert I already replaced the commands from the readme with the .librewolf directory but i didn't know the thing with the /usr/lib so i linked them now but it still doesn't work so here is the output of the commands:

```fish
# ls -hal ~/.librewolf/native-messaging-hosts
total 16K
drwxr-xr-x 2 rajala1404 rajala1404 4.0K Oct 27 01:03 ./
drwx------ 5 rajala1404 rajala1404 4.0K Oct 26 18:29 ../
-rw-r--r-- 1 rajala1404 rajala1404  220 Oct 24 20:41 darkreader.json
-rw-r--r-- 1 rajala1404 rajala1404  254 Oct 27 01:03 pywalfox.json

# ls -hal /opt/darkreader-pywal
total 16K
drwxr-xr-x  2 root root 4.0K Oct 24 19:34 ./
drwxr-xr-x 15 root root 4.0K Oct 24 19:33 ../
-rwxr-xr-x  1 root root  674 Oct 24 19:34 index.js*
-rw-r--r--  1 root root  811 Oct 24 19:34 protocol.js

# ls -hal /usr/lib/librewolf/native-messaging-hosts/
total 12K
drwxr-xr-x 2 root root 4.0K Oct 27 02:42 ./
drwxr-xr-x 3 root root 4.0K Oct 24 19:35 ../
-rw-r--r-- 1 root root  254 Oct 24 19:35 pywalfox.json
```
Browser console:

![image](https://github.com/user-attachments/assets/5539884b-4268-46c3-b8b7-baf27e5f7afe)

But this error seems to be the problem:
```
ExtensionError: No such native application darkreader [ExtensionUtils.sys.mjs:48:5](resource://gre/modules/ExtensionUtils.sys.mjs)
    ExtensionError resource://gre/modules/ExtensionUtils.sys.mjs:48
    startupPromise resource://gre/modules/NativeMessaging.sys.mjs:80
```

**Comment by alexhulbert** [comment]
I noticed a typo in the readme. It said "studio" instead of "stdio". Try editing the darkreader.json file to match. If that doesn't work, copy it into the other /usr/ directory that also contains the pywalfox.json.

**Comment by Rajala1404** [comment]
Yep the typo was the problem but do you know how can I get pywal to generate a transparent background because even if I give it a transparent hex it crashes because it use hex to rgb and the -a option does nothing

**Comment by alexhulbert** [comment]
Pywal doesn't work well with transparency in my experience. Especially not in Firefox or chrome. That's why I created HyprChroma. You can find the installation instructions in the readme. If you're using a different window manager / desktop let me know and I can give you alternative instructions.

**Comment by Rajala1404** [comment]
Ok thanks and the README.md has also a typo because hyprchrome (the command to enable) is written in lower case
```
rajala1404@archlinuxgayming ~> hyprpm enable Hyprchroma
✖ Couldn't enable plugin (missing?)
rajala1404@archlinuxgayming ~ [1]> hyprpm enable hyprchroma
✔ Enabled hyprchroma
✔ Ensuring plugin load state
✔ Loaded hyprchroma
✔ Plugin load state ensured
```
